# Used for binary releases.
version: 1
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo

goos: linux
goarch: amd64
dir: internal/builders/container/
binary: slsa-generator-container-{{ .Os }}-{{ .Arch }}
