name: 'Checkout a repository for a Go project'
description: 'Checkout a Go project's repository and setup the Go environment'
inputs:
  repository:
    description: 'Repository name with owner.'
    required: false
    # Same default as https://github.com/actions/checkout/blob/main/action.yml#L6.
    default: ${{ github.repository }}
  ref:
    # Note: the logic is fairly involved https://github.com/actions/checkout/blob/main/src/ref-helper.ts, 
    # so we do not attemt to resolve it ourselves or provide a default value. We let the official actions/checkout
    # do it for us.
    description: 'The branch, tag or SHA to checkout.'
    required: false
  token:
    description: 'The token to use.'
    required: false
    # Same default as https://github.com/actions/checkout/blob/main/action.yml#L24.
    default: ${{ github.token }}
  go-version:
    description: 'The Go version to use, as expected by https://github.com/actions/setup-go.'
    required: true

runs:
  using: "composite"
  steps:
  REVERT for safety in case they set default value in the futuer
    - name: Checkout the repository
      uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2.3.4
      with:
        fetch-depth: 1
        persist-credentials: false
        repository: "${{ inputs.repository }}"
        # Note: ref may be ""; in this case the Action will resolve it for us.
        # It is important that the ref has no default set (https://github.com/actions/checkout/blob/main/action.yml#L7-L11),
        # because setting an empty value would overwrite the default value and fail.
        ref: "${{ inputs.ref }}"
        token: "${{ inputs.token }}"

    - name: Set up Go environment
      uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # v3.2.0
      with:
        go-version: "${{ inputs.go-version }}"