name: "Checkout a project for a Go project"
description: "Checkout and setup the environment for a Go project"
inputs:
  token:
    description: "The token to use."
    required: false
    # Same default as https://github.com/actions/checkout/blob/main/action.yml#L24.
    default: ${{ github.token }}
  go-version:
    description: "The Go version to use, as expected by https://github.com/actions/setup-go."
    required: true

runs:
  using: "composite"
  steps:
    # Note: this assumes to top-level re-usable workflow
    # has checkout'ed the builder repository using
    # `.github/actions/secure-builder-checkout`.
    - name: Checkout the repository with user ref
      uses: ./__BUILDER_CHECKOUT_DIR__/.github/actions/secure-project-checkout
      with:
        token: ${{ inputs.token }}

    - name: Set up Go environment
      uses: actions/setup-go@268d8c0ca0432bb2cf416faae41297df9d262d7f # tag=v3.3.0
      with:
        go-version: ${{ inputs.go-version }}
