name: pre-submit actions

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  checkout:
    name: verify no checkout in Actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: |

        pwd
        ls
        cd .github
        tree
        
      - run: ./.github/workflows/scripts/pre-submit.actions.checkout.sh
          
